# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Plutus-Tests'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github'
    repositoryName: 'vekt0R-HUB/Project-Plutus'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'release-v1.*'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
    
# - task: Docker@2
#   inputs:
#     containerRegistry: 'docker-hub'
#     repository: 'zealotalgo/project-plutus'
#     command: 'build'
#     Dockerfile: 'dockerfile'
#     buildContext: '**'
    
# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: |
#       echo Hello, world!