# This is a basic workflow that is manually triggered

name: Auto-Update

on:
  push:
    branches:
      - main

jobs:
  auto_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          repository: owner/repo1
      - name: Push changes
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: main
          repository: owner/repo2
        
